import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;
/*
 * JTrackFinder.java
 *
 * Created on May 7, 2004, 11:29 AM
 */

/**
 *
 * @author  Kevin Ziemer
 */
public class JTrackFinder extends JFrame {
    
    private PlotPanel myPlotPanel;
    private IntPoint theData[];
    private TrackControlPanel myControlPanel;
    private UIManager.LookAndFeelInfo looks[];
    
    
    /** Creates new form JTrackFinder */
    public JTrackFinder() {
        initComponents();
    }
    public JTrackFinder(IntPoint inputData[],int xWidth,int yWidth)
    {
        super("Track Locator");
        initComponents();
        theData = inputData;
        Container container = getContentPane();
        container.setLayout( new BorderLayout() );
        
        myPlotPanel = new PlotPanel(theData);
        myPlotPanel.setBackground(Color.white);
        myPlotPanel.setPreferredSize(new Dimension(xWidth,yWidth));
        
        JScrollPane plotScroller = new JScrollPane(myPlotPanel);
	
        myControlPanel = new TrackControlPanel(myPlotPanel);

	JScrollPane controlScroller = new JScrollPane(myControlPanel);
		
	
        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,plotScroller, controlScroller);
        splitPane.setDividerLocation(xWidth);
        splitPane.setDividerSize(8);
        splitPane.setOneTouchExpandable(true);
                
        
        //container.add(myPlotPanel);
        container.add(splitPane);
        setSize(xWidth + 250, yWidth);
        setVisible(true);
        
        try
        {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception e)
        {
            e.printStackTrace();
            
        }
        
        //container.add(myPlotPanel);
        //setSize(xWidth + 200, yWidth);
        //setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    public IntPoint[] getTrackCoords()
    {
        return myPlotPanel.getTrackCoords();
    }
    public IntPoint[] getOuterCoords()
    {
        return myPlotPanel.getOuterCoords();
    }
    public IntPoint[] getInnerCoords()
    {
        return myPlotPanel.getInnerCoords();
    }
    public boolean clockwiseCheck()
    {
        return myControlPanel.isCW();
    }
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        setVisible(false);
    }//GEN-LAST:event_exitForm
    
    public void close()
    {
        myPlotPanel = null;
        myControlPanel = null;
        theData = null;
        setVisible(false);
        System.gc();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JTrackFinder().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
